server.port=8083
spring.application.name=car-details-validation-service

# Eureka Discovery Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

