server.port=8083
spring.application.name=car-details-validation-service

# Eureka Discovery Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
